# # # # # # # # # #
#  K i k o f r i  #
# # # # # # # # # #

# # # # #
# Used as meta-data for 'head.html' among 
# other things.
#
# Basic, either your jekyll site's name or
# an organization.
name: "A muse, amuse"
description: "I'm always amused and amusing you"

# This should be a person of some sort.
author: "AE"

# Would make sense to use the 'name:' above
# here. This is an alternative title.
title: "A muse, amuse"

# 'en_US' is the default language. Enter a
# new default language here. Making 'en_US'
# an alternative language. See 'head.html'
lang:

# Default post and page image if it's those
# are unspecified.

# I just set this to whatever the above
# image value is.
# Could be some other image though.
logo:
#
# # # # #

# URL-stuff, don't forget the 'http...'-part
url: "https://amusinghouse.com"
#baseurl: ""
permalink: /:year/:month/:day/:title.html

# Markdown
markdown: kramdown

# Navigation
nav:
 - name: "about"
   href: "/about"

 - name: "tags"
   href: "/tags"

 - name: "feed"
   href: "/feed.xml"

exclude:
  - vendor
  - .jekyll-cache
